# Generated by Django 5.2.3 on 2025-09-09 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField()),
                ('location', models.CharField(max_length=300)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/')),
                ('amenities', models.TextField(help_text='List amenities separated by commas')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VenueAdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='venue.venue')),
            ],
            options={
                'verbose_name': 'Venue Additional Images',
                'verbose_name_plural': 'Venue Additional Images',
            },
        ),
    ]
