# Generated by Django 4.2.7 on 2025-07-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAdditionalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='venue.venue')),
            ],
            options={
                'verbose_name': 'Venue Additional Images',
                'verbose_name_plural': 'Venue Additional Images',
            },
        ),
    ]
